pipeline {
    agent any 
        stages {
            stage('echo'){
                steps{
                    sh """
                      yum install java-1.8.0-openjdk-devel wget -y
                      yum install git -y 
                      yum install maven -y
                    """
                }
            }
        }
}
